HOST = "localhost"
PORT = 12432

# DELIMITER
DELIMITER = "%%"

# REQUEST COMMANDS
SQUARE = "SQUARE"
CUBE = "CUBE"
LARGEST = "LARGEST"
MY_LARGEST = "MYLARGEST"

# FIXED RESPONSE VALUES
NO_NUMBER = "PLEASE_SUPPLY_NUMBER"
UNKNOWN = "UNKNOWN_COMMAND"