# Location information
PORT = 23450
HOST = "localhost"

# Delimiters
BASE_DELIMITER = "%%"
TOPPING_DELIMITER = "~~"
SECTION_DELIMITER = "##"

# Request headers/actions
TOPPINGS="TOPPINGS"
SIZES="SIZES"
CREATE="CREATE"
GET_PIZZA="GET_PIZZA"
GET_ORDER="GET_ORDER"


# Responses
UNKNOWN = "UNKNOWN_COMMAND"
NO_REJECTED = "NO_REJECTED_TOPPINGS"
INVALID_SIZE = "INVALID_SIZE"
INVALID_NAME = "INVALID_PIZZA_NAME"
EMPTY_ORDER = "NO_ITEMS"